/**
 * External dependencies
 */
import React from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';

/**
 * Internal dependencies
 */
import Card from 'components/card';
import { localize } from 'i18n-calypso';
import { getTwoFactorPushPollSuccess } from 'state/login/selectors';
import {
	startPollAppPushAuth,
	stopPollAppPushAuth,
} from 'state/login/actions';

class WaitingTwoFactorNotificationApproval extends React.Component {
	componentDidMount() {
		this.props.startPollAppPushAuth();
	}

	componentWillUnmount() {
		this.props.stopPollAppPushAuth();
	}

	componentWillReceiveProps( nextProps ) {
		if ( ! this.props.pushSuccess && nextProps.pushSuccess ) {
			window.location.replace( '/' );
		}
	}

	render() {
		const {
			translate,
			pushSuccess,
		} = this.props;

		return <form>
			<Card className="two-factor-authentication__push-notification-screen is-compact">
				<p>
					{ pushSuccess ? translate( 'Awesome, you are now logged in! One moment while we take you to homepage…' )
						: translate( 'We just sent a push notification to your WordPress mobile app. ' +
						'Swipe or tap to open and verify your login.' ) }
				</p>
				<div>
					<img className="two-factor-authentication__auth-code-preview" src="/calypso/images/login/pushauth.svg" />
				</div>
				<p>
					{ translate( 'Or, type in the verification code generated by your Authenticator app' +
						' or sent via text.' ) }
				</p>
			</Card>
			<Card className="two-factor-authentication__form-action is-compact">
				<p>
					{ translate( 'Or, continue to your account using:' ) }
				</p>
				<p>
					<a href="#">{ translate( 'A recovery code via text' ) }</a>
				</p>
				<p>
					<a href="#">{ translate( 'An Authenticator application' ) }</a>
				</p>
			</Card>
		</form>;
	}
}

WaitingTwoFactorNotificationApproval.propTypes = {
	pushSuccess: React.PropTypes.bool.required,
	startPollAppPushAuth: React.PropTypes.func.required,
	stopPollAppPushAuth: React.PropTypes.func.required,
};

export default connect(
	state => ( {
		pushSuccess: getTwoFactorPushPollSuccess( state ),
	} ),
	dispatch => bindActionCreators( {
		startPollAppPushAuth,
		stopPollAppPushAuth,
	}, dispatch )
)( localize( WaitingTwoFactorNotificationApproval ) );
